SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP SCHEMA IF EXISTS `lddb` ;
CREATE SCHEMA IF NOT EXISTS `lddb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `lddb` ;

-- -----------------------------------------------------
-- Table `lddb`.`DESIGNATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lddb`.`DESIGNATION` ;

CREATE  TABLE IF NOT EXISTS `lddb`.`DESIGNATION` (
  `DESIGNATION_ID` INT(5) NOT NULL ,
  `NAME` VARCHAR(20) NOT NULL ,
  `DESCRIPTION` VARCHAR(256) NULL ,
  `CREATED_BY` VARCHAR(10) NOT NULL ,
  `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  `UPDATED_BY` VARCHAR(10) NULL ,
  `UPDATED_DATE` TIMESTAMP NULL ,
  `ACTIVE` VARCHAR(1) NOT NULL ,
  PRIMARY KEY (`DESIGNATION_ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lddb`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lddb`.`USER` ;

CREATE  TABLE IF NOT EXISTS `lddb`.`USER` (
  `ID` INT(5) NOT NULL ,
  `USER_ID` VARCHAR(10) NOT NULL ,
  `FIRST_NAME` VARCHAR(20) NOT NULL ,
  `LAST_NAME` VARCHAR(20) NOT NULL ,
  `DESIGNATION` INT(5) NOT NULL ,
  `MANAGER` INT(5) NULL ,
  `ACTIVE` VARCHAR(1) NOT NULL ,
  `ROLE` VARCHAR(10) NOT NULL ,
  `CREATED_BY` VARCHAR(10) NOT NULL ,
  `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  `UPDATED_BY` VARCHAR(10) NULL ,
  `UPDATED_DATE` TIMESTAMP NULL ,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT `USER_DESIGNATION`
    FOREIGN KEY (`DESIGNATION` )
    REFERENCES `lddb`.`DESIGNATION` (`DESIGNATION_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `USER_ID`
    FOREIGN KEY (`MANAGER` )
    REFERENCES `lddb`.`USER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `USER_ID_UNIQUE` ON `lddb`.`USER` (`USER_ID` ASC) ;

CREATE INDEX `USER_DESIGNATION_idx` ON `lddb`.`USER` (`DESIGNATION` ASC) ;

CREATE INDEX `USER_ID_idx` ON `lddb`.`USER` (`MANAGER` ASC) ;


-- -----------------------------------------------------
-- Table `lddb`.`TRAINING_COURSE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lddb`.`TRAINING_COURSE` ;

CREATE  TABLE IF NOT EXISTS `lddb`.`TRAINING_COURSE` (
  `TRAINING_COURSE_ID` INT(5) NOT NULL ,
  `NAME` VARCHAR(20) NOT NULL ,
  `DESCRIPTION` VARCHAR(256) NULL ,
  `CREATED_BY` VARCHAR(10) NOT NULL ,
  `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  `UPDATED_BY` VARCHAR(10) NULL ,
  `UPDATED_DATE` TIMESTAMP NULL ,
  PRIMARY KEY (`TRAINING_COURSE_ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lddb`.`TRAINING`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lddb`.`TRAINING` ;

CREATE  TABLE IF NOT EXISTS `lddb`.`TRAINING` (
  `TRAINING_ID` INT(5) NOT NULL ,
  `TRAINING_COURSE_ID` INT(5) NOT NULL ,
  `DURATION` INT(11) NOT NULL ,
  `SCHEDULED_DATE` DATE NULL ,
  `CREATED_BY` VARCHAR(10) NOT NULL ,
  `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  `UPDATED_BY` VARCHAR(10) NULL ,
  `UPDATED_DATE` TIMESTAMP NULL ,
  `ACTIVE` VARCHAR(1) NOT NULL ,
  `OPEN_FOR_NOMINATION` VARCHAR(1) NOT NULL ,
  PRIMARY KEY (`TRAINING_ID`) ,
  CONSTRAINT `TRAINING_COURSE_ID`
    FOREIGN KEY (`TRAINING_COURSE_ID` )
    REFERENCES `lddb`.`TRAINING_COURSE` (`TRAINING_COURSE_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `TRAINING_COURSE_ID_idx` ON `lddb`.`TRAINING` (`TRAINING_COURSE_ID` ASC) ;


-- -----------------------------------------------------
-- Table `lddb`.`TRAINING_USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lddb`.`TRAINING_USER` ;

CREATE  TABLE IF NOT EXISTS `lddb`.`TRAINING_USER` (
  `TRAINING_ID` INT(5) NOT NULL ,
  `USER_ID` INT(5) NOT NULL ,
  `CREATED_BY` VARCHAR(10) NOT NULL ,
  `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  `UPDATED_BY` VARCHAR(10) NULL ,
  `UPDATED_DATE` TIMESTAMP NULL ,
  PRIMARY KEY (`TRAINING_ID`, `USER_ID`) ,
  CONSTRAINT `TRAINING_ID_TR`
    FOREIGN KEY (`TRAINING_ID` )
    REFERENCES `lddb`.`TRAINING` (`TRAINING_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TRAINING_USER_ID`
    FOREIGN KEY (`USER_ID` )
    REFERENCES `lddb`.`USER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `TRAINING_ID_idx` ON `lddb`.`TRAINING_USER` (`TRAINING_ID` ASC) ;

CREATE INDEX `USER_ID_idx` ON `lddb`.`TRAINING_USER` (`USER_ID` ASC) ;


-- -----------------------------------------------------
-- Table `lddb`.`TRAINING_NOMINATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lddb`.`TRAINING_NOMINATION` ;

CREATE  TABLE IF NOT EXISTS `lddb`.`TRAINING_NOMINATION` (
  `TRAINING_NOMINATION_ID` INT(5) NOT NULL ,
  `USER_ID` INT(5) NOT NULL ,
  `TRAINING_ID` INT(5) NOT NULL ,
  `APPROVAL_PENDING` VARCHAR(1) NULL ,
  `APPROVED_DENIED` VARCHAR(1) NULL ,
  `APPROVED_DENIED_BY` INT(5) NULL ,
  `ATTENDED` VARCHAR(1) NULL ,
  `NOMINATED_BY` VARCHAR(10) NULL ,
  `CREATED_BY` VARCHAR(10) NOT NULL ,
  `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  `UPDATED_BY` VARCHAR(10) NULL ,
  `UPDATED_DATE` TIMESTAMP NULL ,
  `WITHDRAW_NOMINATION` VARCHAR(1) NULL ,
  PRIMARY KEY (`TRAINING_NOMINATION_ID`) ,
  CONSTRAINT `TN_USER_ID_1`
    FOREIGN KEY (`USER_ID` )
    REFERENCES `lddb`.`USER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TN_TRAINING_ID`
    FOREIGN KEY (`TRAINING_ID` )
    REFERENCES `lddb`.`TRAINING` (`TRAINING_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TN_USER_ID_2`
    FOREIGN KEY (`APPROVED_DENIED_BY` )
    REFERENCES `lddb`.`USER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `user_id_idx` ON `lddb`.`TRAINING_NOMINATION` (`USER_ID` ASC) ;

CREATE INDEX `TN_TRAINING_ID_idx` ON `lddb`.`TRAINING_NOMINATION` (`TRAINING_ID` ASC) ;

CREATE INDEX `TN_USER_ID_2_idx` ON `lddb`.`TRAINING_NOMINATION` (`APPROVED_DENIED_BY` ASC) ;


-- -----------------------------------------------------
-- Table `lddb`.`USER_LOGIN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lddb`.`USER_LOGIN` ;

CREATE  TABLE IF NOT EXISTS `lddb`.`USER_LOGIN` (
  `ID` INT(5) NOT NULL ,
  `USER_ID` INT(5) NOT NULL ,
  `PASSWORD` VARCHAR(10) NOT NULL ,
  `CREATED_BY` VARCHAR(10) NOT NULL ,
  `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  `UPDATED_BY` VARCHAR(10) NULL ,
  `UPDATED_DATE` TIMESTAMP NULL ,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT `UL_USER_ID`
    FOREIGN KEY (`USER_ID` )
    REFERENCES `lddb`.`USER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `UL_USER_ID_idx` ON `lddb`.`USER_LOGIN` (`USER_ID` ASC) ;


-- -----------------------------------------------------
-- Table `lddb`.`PROJECT_DOCUMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lddb`.`PROJECT_DOCUMENT` ;

CREATE  TABLE IF NOT EXISTS `lddb`.`PROJECT_DOCUMENT` (
  `PROJECT_DOCUMENT_ID` INT(5) NOT NULL ,
  `DOCUMENT_NAME` VARCHAR(20) NOT NULL ,
  `DOCUMENT_DESCRIPTION` VARCHAR(256) NOT NULL ,
  `DOCUMENT_TYPE` VARCHAR(10) NOT NULL ,
  `CREATED_BY` VARCHAR(10) NOT NULL ,
  `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  `UPDATED_BY` VARCHAR(10) NULL ,
  `UPDATED_DATE` TIMESTAMP NULL ,
  PRIMARY KEY (`PROJECT_DOCUMENT_ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lddb`.`PROJECT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lddb`.`PROJECT` ;

CREATE  TABLE IF NOT EXISTS `lddb`.`PROJECT` (
  `PROJECT_ID` INT(5) NOT NULL ,
  `NAME` VARCHAR(20) NOT NULL ,
  `DESCRIPTION` LONGTEXT NOT NULL ,
  `START_DATE` DATE NOT NULL ,
  `END_DATE` DATE NULL ,
  `PROJECT_DOCUMENT_ID` INT(5) NULL ,
  `CREATED_BY` VARCHAR(10) NOT NULL ,
  `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  `UPDATED_BY` VARCHAR(10) NULL ,
  `UPDATED_DATE` TIMESTAMP NULL ,
  `ACTIVE` VARCHAR(1) NOT NULL ,
  PRIMARY KEY (`PROJECT_ID`) ,
  CONSTRAINT `PROJ_DOC_ID`
    FOREIGN KEY (`PROJECT_DOCUMENT_ID` )
    REFERENCES `lddb`.`PROJECT_DOCUMENT` (`PROJECT_DOCUMENT_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `PROJ_DOC_ID_idx` ON `lddb`.`PROJECT` (`PROJECT_DOCUMENT_ID` ASC) ;


-- -----------------------------------------------------
-- Table `lddb`.`PROJECT_ROLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lddb`.`PROJECT_ROLE` ;

CREATE  TABLE IF NOT EXISTS `lddb`.`PROJECT_ROLE` (
  `ROLE_ID` INT(5) NOT NULL ,
  `ROLE_NAME` VARCHAR(10) NOT NULL ,
  `ROLE_DESCRIPTION` VARCHAR(256) NOT NULL ,
  `CREATED_BY` VARCHAR(10) NOT NULL ,
  `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  `UPDATED_BY` VARCHAR(10) NULL ,
  `UPDATED_DATE` TIMESTAMP NULL ,
  `ACTIVE` VARCHAR(1) NOT NULL ,
  PRIMARY KEY (`ROLE_ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lddb`.`USER_PROJECT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lddb`.`USER_PROJECT` ;

CREATE  TABLE IF NOT EXISTS `lddb`.`USER_PROJECT` (
  `ID` INT(5) NOT NULL ,
  `USER_ID` INT(5) NOT NULL ,
  `PROJECT_ID` INT(5) NOT NULL ,
  `ROLE` INT(5) NULL ,
  `START_DATE` DATE NOT NULL ,
  `END_DATE` DATE NULL ,
  `CREATED_BY` VARCHAR(10) NOT NULL ,
  `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  `UPDATED_BY` VARCHAR(10) NULL ,
  `UPDATED_DATE` TIMESTAMP NULL ,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT `UP_USER_ID`
    FOREIGN KEY (`USER_ID` )
    REFERENCES `lddb`.`USER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `UP_PROJECT_ID`
    FOREIGN KEY (`PROJECT_ID` )
    REFERENCES `lddb`.`PROJECT` (`PROJECT_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `UP_ROLE_ID`
    FOREIGN KEY (`ROLE` )
    REFERENCES `lddb`.`PROJECT_ROLE` (`ROLE_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `UP_USER_ID_idx` ON `lddb`.`USER_PROJECT` (`USER_ID` ASC) ;

CREATE INDEX `UP_PROJECT_ID_idx` ON `lddb`.`USER_PROJECT` (`PROJECT_ID` ASC) ;

CREATE INDEX `UP_ROLE_ID_idx` ON `lddb`.`USER_PROJECT` (`ROLE` ASC) ;


-- -----------------------------------------------------
-- Table `lddb`.`USER_PROJECT_APPRECIATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lddb`.`USER_PROJECT_APPRECIATION` ;

CREATE  TABLE IF NOT EXISTS `lddb`.`USER_PROJECT_APPRECIATION` (
  `ID` INT(5) NOT NULL ,
  `USER_ID` INT(5) NOT NULL ,
  `PROJECT_ID` INT(5) NOT NULL ,
  `APPRECIATION_FROM` VARCHAR(20) NOT NULL ,
  `APPRECIATION_DETAILS` VARCHAR(256) NOT NULL ,
  `APPRECIATION_DATE` DATE NOT NULL ,
  `CREATED_BY` VARCHAR(10) NOT NULL ,
  `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  `UPDATED_BY` VARCHAR(10) NULL ,
  `UPDATED_DATE` TIMESTAMP NULL ,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT `UPA_USER_ID`
    FOREIGN KEY (`USER_ID` )
    REFERENCES `lddb`.`USER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `UPA_PROJECT_ID`
    FOREIGN KEY (`PROJECT_ID` )
    REFERENCES `lddb`.`PROJECT` (`PROJECT_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `project_id_idx` ON `lddb`.`USER_PROJECT_APPRECIATION` (`PROJECT_ID` ASC) ;

CREATE INDEX `UPA_USER_ID_idx` ON `lddb`.`USER_PROJECT_APPRECIATION` (`USER_ID` ASC) ;


-- -----------------------------------------------------
-- Table `lddb`.`CERTIFICATION_DETAILS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lddb`.`CERTIFICATION_DETAILS` ;

CREATE  TABLE IF NOT EXISTS `lddb`.`CERTIFICATION_DETAILS` (
  `ID` INT(5) NOT NULL ,
  `NAME` VARCHAR(20) NOT NULL ,
  `DESCRIPTION` VARCHAR(256) NOT NULL ,
  `USER_ID` INT(5) NOT NULL ,
  `CERTIFICATION_DATE` DATE NOT NULL ,
  `CREATED_BY` VARCHAR(10) NOT NULL ,
  `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  `UPDATED_BY` VARCHAR(10) NULL ,
  `UPDATED_DATE` TIMESTAMP NULL ,
  `ACTIVE` VARCHAR(1) NOT NULL ,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT `CD_USER_ID`
    FOREIGN KEY (`USER_ID` )
    REFERENCES `lddb`.`USER` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `CD_USER_ID_idx` ON `lddb`.`CERTIFICATION_DETAILS` (`USER_ID` ASC) ;

USE `lddb` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `lddb`.`DESIGNATION`
-- -----------------------------------------------------
START TRANSACTION;
USE `lddb`;
INSERT INTO `lddb`.`DESIGNATION` (`DESIGNATION_ID`, `NAME`, `DESCRIPTION`, `CREATED_BY`, `CREATED_DATE`, `UPDATED_BY`, `UPDATED_DATE`, `ACTIVE`) VALUES (1, 'ADMIN', 'DEFAULT ADMIN', 'SYSTEM', NOW(), NULL, NULL, 'Y');
INSERT INTO `lddb`.`DESIGNATION` (`DESIGNATION_ID`, `NAME`, `DESCRIPTION`, `CREATED_BY`, `CREATED_DATE`, `UPDATED_BY`, `UPDATED_DATE`, `ACTIVE`) VALUES (2, 'SE', 'SOFTWARE ENGINEER', 'SYSTEM', NOW(), NULL, NULL, 'Y');
INSERT INTO `lddb`.`DESIGNATION` (`DESIGNATION_ID`, `NAME`, `DESCRIPTION`, `CREATED_BY`, `CREATED_DATE`, `UPDATED_BY`, `UPDATED_DATE`, `ACTIVE`) VALUES (3, 'SSE', 'SENIOR SOFTWARE ENGINEER', 'SYSTEM', NOW(), NULL, NULL, 'Y');
INSERT INTO `lddb`.`DESIGNATION` (`DESIGNATION_ID`, `NAME`, `DESCRIPTION`, `CREATED_BY`, `CREATED_DATE`, `UPDATED_BY`, `UPDATED_DATE`, `ACTIVE`) VALUES (4, 'P1', 'P1', 'SYSTEM', NOW(), NULL, NULL, 'Y');
INSERT INTO `lddb`.`DESIGNATION` (`DESIGNATION_ID`, `NAME`, `DESCRIPTION`, `CREATED_BY`, `CREATED_DATE`, `UPDATED_BY`, `UPDATED_DATE`, `ACTIVE`) VALUES (5, 'P2', 'P2', 'SYSTEM', NOW(), NULL, NULL, 'Y');
INSERT INTO `lddb`.`DESIGNATION` (`DESIGNATION_ID`, `NAME`, `DESCRIPTION`, `CREATED_BY`, `CREATED_DATE`, `UPDATED_BY`, `UPDATED_DATE`, `ACTIVE`) VALUES (6, 'P3', 'P3', 'SYSTEM', NOW(), NULL, NULL, 'Y');
INSERT INTO `lddb`.`DESIGNATION` (`DESIGNATION_ID`, `NAME`, `DESCRIPTION`, `CREATED_BY`, `CREATED_DATE`, `UPDATED_BY`, `UPDATED_DATE`, `ACTIVE`) VALUES (7, 'P4', 'P4', 'SYSTEM', NOW(), NULL, NULL, 'Y');
INSERT INTO `lddb`.`DESIGNATION` (`DESIGNATION_ID`, `NAME`, `DESCRIPTION`, `CREATED_BY`, `CREATED_DATE`, `UPDATED_BY`, `UPDATED_DATE`, `ACTIVE`) VALUES (9, 'M1', 'M1', 'SYSTEM', NOW(), NULL, NULL, 'Y');
INSERT INTO `lddb`.`DESIGNATION` (`DESIGNATION_ID`, `NAME`, `DESCRIPTION`, `CREATED_BY`, `CREATED_DATE`, `UPDATED_BY`, `UPDATED_DATE`, `ACTIVE`) VALUES (10, 'M2', 'M2', 'SYSTEM', NOW(), NULL, NULL, 'Y');
INSERT INTO `lddb`.`DESIGNATION` (`DESIGNATION_ID`, `NAME`, `DESCRIPTION`, `CREATED_BY`, `CREATED_DATE`, `UPDATED_BY`, `UPDATED_DATE`, `ACTIVE`) VALUES (11, 'M3', 'M3', 'SYSTEM', NOW(), NULL, NULL, 'Y');
INSERT INTO `lddb`.`DESIGNATION` (`DESIGNATION_ID`, `NAME`, `DESCRIPTION`, `CREATED_BY`, `CREATED_DATE`, `UPDATED_BY`, `UPDATED_DATE`, `ACTIVE`) VALUES (12, 'M4', 'M4', 'SYSTEM', NOW(), NULL, NULL, 'Y');
INSERT INTO `lddb`.`DESIGNATION` (`DESIGNATION_ID`, `NAME`, `DESCRIPTION`, `CREATED_BY`, `CREATED_DATE`, `UPDATED_BY`, `UPDATED_DATE`, `ACTIVE`) VALUES (13, 'M5', 'M5', 'SYSTEM', NOW(), NULL, NULL, 'Y');
INSERT INTO `lddb`.`DESIGNATION` (`DESIGNATION_ID`, `NAME`, `DESCRIPTION`, `CREATED_BY`, `CREATED_DATE`, `UPDATED_BY`, `UPDATED_DATE`, `ACTIVE`) VALUES (14, 'M6', 'M6', 'SYSTEM', NOW(), NULL, NULL, 'Y');
INSERT INTO `lddb`.`DESIGNATION` (`DESIGNATION_ID`, `NAME`, `DESCRIPTION`, `CREATED_BY`, `CREATED_DATE`, `UPDATED_BY`, `UPDATED_DATE`, `ACTIVE`) VALUES (8, 'P5', 'P5', 'SYSTEM', NOW(), NULL, NULL, 'Y');

COMMIT;

-- -----------------------------------------------------
-- Data for table `lddb`.`USER`
-- -----------------------------------------------------
START TRANSACTION;
USE `lddb`;
INSERT INTO `lddb`.`USER` (`ID`, `USER_ID`, `FIRST_NAME`, `LAST_NAME`, `DESIGNATION`, `MANAGER`, `ACTIVE`, `ROLE`, `CREATED_BY`, `CREATED_DATE`, `UPDATED_BY`, `UPDATED_DATE`) VALUES (1, 'ADMIN', 'ADMIN', 'ADMIN', 1, NULL, 'Y', 'ADMIN', 'SYSTEM', NOW(), NULL, NULL);

COMMIT;

-- -----------------------------------------------------
-- Data for table `lddb`.`USER_LOGIN`
-- -----------------------------------------------------
START TRANSACTION;
USE `lddb`;
INSERT INTO `lddb`.`USER_LOGIN` (`ID`, `USER_ID`, `PASSWORD`, `CREATED_BY`, `CREATED_DATE`, `UPDATED_BY`, `UPDATED_DATE`) VALUES (1, 1, 'admin', 'SYSTEM', NOW(), NULL, NULL);

COMMIT;
